// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorDashboard.Api.Data;

#nullable disable

namespace SensorDashboard.Api.Data.Migrations
{
    [DbContext(typeof(DigitalTwinDbContext))]
    [Migration("20260928205623_WarehouseCoordinates")]
    partial class WarehouseCoordinates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("metadata")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SensorDashboard.Api.Data.Metadata.Sensor", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MaxTemperatureF")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinTemperatureF")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Sensors", "metadata", t =>
                        {
                            t.HasCheckConstraint("CK_Sensors_TemperatureRange", "[MinTemperatureF] < [MaxTemperatureF]");
                        });

                    b.HasData(
                        new
                        {
                            Id = "WH-SEA-FRG-01",
                            IsActive = true,
                            Location = "Dairy Cooler",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            WarehouseId = "WH-SEA"
                        },
                        new
                        {
                            Id = "WH-SEA-FRG-02",
                            IsActive = true,
                            Location = "Produce Cooler",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            WarehouseId = "WH-SEA"
                        },
                        new
                        {
                            Id = "WH-SEA-FRG-03",
                            IsActive = true,
                            Location = "Meat Locker",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            WarehouseId = "WH-SEA"
                        },
                        new
                        {
                            Id = "WH-SEA-FRG-04",
                            IsActive = true,
                            Location = "Loading Dock Fridge",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            WarehouseId = "WH-SEA"
                        },
                        new
                        {
                            Id = "WH-PDX-FRG-01",
                            IsActive = true,
                            Location = "Walk-in Cooler A",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            WarehouseId = "WH-PDX"
                        },
                        new
                        {
                            Id = "WH-PDX-FRG-02",
                            IsActive = true,
                            Location = "Walk-in Cooler B",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            WarehouseId = "WH-PDX"
                        },
                        new
                        {
                            Id = "WH-PDX-FRG-03",
                            IsActive = true,
                            Location = "Pharma Fridge",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            WarehouseId = "WH-PDX"
                        },
                        new
                        {
                            Id = "WH-BOI-FRG-01",
                            IsActive = true,
                            Location = "Beverage Cooler",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            WarehouseId = "WH-BOI"
                        },
                        new
                        {
                            Id = "WH-BOI-FRG-02",
                            IsActive = true,
                            Location = "Dairy Cooler",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            WarehouseId = "WH-BOI"
                        },
                        new
                        {
                            Id = "WH-BOI-FRG-03",
                            IsActive = true,
                            Location = "Produce Cooler",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            WarehouseId = "WH-BOI"
                        },
                        new
                        {
                            Id = "WH-BOI-FRG-04",
                            IsActive = true,
                            Location = "Floral Fridge",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            WarehouseId = "WH-BOI"
                        },
                        new
                        {
                            Id = "WH-BOI-FRG-05",
                            IsActive = true,
                            Location = "Returns Fridge",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            WarehouseId = "WH-BOI"
                        });
                });

            modelBuilder.Entity("SensorDashboard.Api.Data.Metadata.Warehouse", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses", "metadata", t =>
                        {
                            t.HasCheckConstraint("CK_Warehouses_Latitude", "[Latitude] BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_Warehouses_Longitude", "[Longitude] BETWEEN -180 AND 180");
                        });

                    b.HasData(
                        new
                        {
                            Id = "WH-SEA",
                            City = "Seattle, WA",
                            Latitude = 47.606200000000001,
                            Longitude = -122.3321,
                            Name = "Seattle Distribution Center"
                        },
                        new
                        {
                            Id = "WH-PDX",
                            City = "Portland, OR",
                            Latitude = 45.5152,
                            Longitude = -122.6784,
                            Name = "Portland Cold Storage"
                        },
                        new
                        {
                            Id = "WH-BOI",
                            City = "Boise, ID",
                            Latitude = 43.615000000000002,
                            Longitude = -116.20229999999999,
                            Name = "Boise Fulfillment Hub"
                        });
                });

            modelBuilder.Entity("SensorDashboard.Api.Data.Metadata.Sensor", b =>
                {
                    b.HasOne("SensorDashboard.Api.Data.Metadata.Warehouse", "Warehouse")
                        .WithMany("Sensors")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SensorDashboard.Api.Data.Metadata.Warehouse", b =>
                {
                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
