// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SensorDashboard.Api.Data;

#nullable disable

namespace SensorDashboard.Api.Data.Migrations
{
    [DbContext(typeof(DigitalTwinDbContext))]
    [Migration("20260929000844_QueueAvailableAtPrecision")]
    partial class QueueAvailableAtPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("metadata")
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SensorDashboard.Api.Data.Alerts.Alert", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EscalatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<double?>("PeakTemperature")
                        .HasColumnType("float");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .IsUnicode(false)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("SensorId", "Kind")
                        .IsUnique()
                        .HasDatabaseName("UX_Alerts_Active")
                        .HasFilter("[ClosedAt] IS NULL");

                    b.HasIndex("WarehouseId", "OpenedAt");

                    b.ToTable("Alerts", "ops");
                });

            modelBuilder.Entity("SensorDashboard.Api.Data.Metadata.Sensor", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("MaxTemperatureF")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("MinTemperatureF")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<double>("PositionX")
                        .HasColumnType("float");

                    b.Property<double>("PositionZ")
                        .HasColumnType("float");

                    b.Property<double>("RotationDegrees")
                        .HasColumnType("float");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("WarehouseId")
                        .IsRequired()
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Sensors", "metadata", t =>
                        {
                            t.HasCheckConstraint("CK_Sensors_Position", "[PositionX] >= 0 AND [PositionZ] >= 0");

                            t.HasCheckConstraint("CK_Sensors_TemperatureRange", "[MinTemperatureF] < [MaxTemperatureF]");
                        });

                    b.HasData(
                        new
                        {
                            Id = "WH-SEA-FRG-01",
                            IsActive = true,
                            Location = "Dairy Cooler",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            PositionX = 6.0,
                            PositionZ = 3.0,
                            RotationDegrees = 0.0,
                            UnitType = "WalkInCooler",
                            WarehouseId = "WH-SEA"
                        },
                        new
                        {
                            Id = "WH-SEA-FRG-02",
                            IsActive = true,
                            Location = "Produce Cooler",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            PositionX = 14.0,
                            PositionZ = 3.0,
                            RotationDegrees = 0.0,
                            UnitType = "WalkInCooler",
                            WarehouseId = "WH-SEA"
                        },
                        new
                        {
                            Id = "WH-SEA-FRG-03",
                            IsActive = true,
                            Location = "Meat Locker",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            PositionX = 22.0,
                            PositionZ = 3.0,
                            RotationDegrees = 0.0,
                            UnitType = "WalkInCooler",
                            WarehouseId = "WH-SEA"
                        },
                        new
                        {
                            Id = "WH-SEA-FRG-04",
                            IsActive = true,
                            Location = "Loading Dock Fridge",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            PositionX = 36.0,
                            PositionZ = 22.0,
                            RotationDegrees = 180.0,
                            UnitType = "ReachInFridge",
                            WarehouseId = "WH-SEA"
                        },
                        new
                        {
                            Id = "WH-PDX-FRG-01",
                            IsActive = true,
                            Location = "Walk-in Cooler A",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            PositionX = 6.0,
                            PositionZ = 3.0,
                            RotationDegrees = 0.0,
                            UnitType = "WalkInCooler",
                            WarehouseId = "WH-PDX"
                        },
                        new
                        {
                            Id = "WH-PDX-FRG-02",
                            IsActive = true,
                            Location = "Walk-in Cooler B",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            PositionX = 14.0,
                            PositionZ = 3.0,
                            RotationDegrees = 0.0,
                            UnitType = "WalkInCooler",
                            WarehouseId = "WH-PDX"
                        },
                        new
                        {
                            Id = "WH-PDX-FRG-03",
                            IsActive = true,
                            Location = "Pharma Fridge",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            PositionX = 28.0,
                            PositionZ = 12.0,
                            RotationDegrees = 270.0,
                            UnitType = "ReachInFridge",
                            WarehouseId = "WH-PDX"
                        },
                        new
                        {
                            Id = "WH-BOI-FRG-01",
                            IsActive = true,
                            Location = "Beverage Cooler",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            PositionX = 10.0,
                            PositionZ = 26.0,
                            RotationDegrees = 180.0,
                            UnitType = "DisplayCase",
                            WarehouseId = "WH-BOI"
                        },
                        new
                        {
                            Id = "WH-BOI-FRG-02",
                            IsActive = true,
                            Location = "Dairy Cooler",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            PositionX = 8.0,
                            PositionZ = 3.0,
                            RotationDegrees = 0.0,
                            UnitType = "WalkInCooler",
                            WarehouseId = "WH-BOI"
                        },
                        new
                        {
                            Id = "WH-BOI-FRG-03",
                            IsActive = true,
                            Location = "Produce Cooler",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            PositionX = 16.0,
                            PositionZ = 3.0,
                            RotationDegrees = 0.0,
                            UnitType = "WalkInCooler",
                            WarehouseId = "WH-BOI"
                        },
                        new
                        {
                            Id = "WH-BOI-FRG-04",
                            IsActive = true,
                            Location = "Floral Fridge",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            PositionX = 20.0,
                            PositionZ = 26.0,
                            RotationDegrees = 180.0,
                            UnitType = "DisplayCase",
                            WarehouseId = "WH-BOI"
                        },
                        new
                        {
                            Id = "WH-BOI-FRG-05",
                            IsActive = true,
                            Location = "Returns Fridge",
                            MaxTemperatureF = 40m,
                            MinTemperatureF = 34m,
                            PositionX = 48.0,
                            PositionZ = 16.0,
                            RotationDegrees = 270.0,
                            UnitType = "ReachInFridge",
                            WarehouseId = "WH-BOI"
                        });
                });

            modelBuilder.Entity("SensorDashboard.Api.Data.Metadata.Warehouse", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(32)
                        .IsUnicode(false)
                        .HasColumnType("varchar(32)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("FloorDepthM")
                        .HasColumnType("float");

                    b.Property<double>("FloorWidthM")
                        .HasColumnType("float");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Warehouses", "metadata", t =>
                        {
                            t.HasCheckConstraint("CK_Warehouses_FloorSize", "[FloorWidthM] > 0 AND [FloorDepthM] > 0");

                            t.HasCheckConstraint("CK_Warehouses_Latitude", "[Latitude] BETWEEN -90 AND 90");

                            t.HasCheckConstraint("CK_Warehouses_Longitude", "[Longitude] BETWEEN -180 AND 180");
                        });

                    b.HasData(
                        new
                        {
                            Id = "WH-SEA",
                            City = "Seattle, WA",
                            FloorDepthM = 25.0,
                            FloorWidthM = 40.0,
                            Latitude = 47.606200000000001,
                            Longitude = -122.3321,
                            Name = "Seattle Distribution Center"
                        },
                        new
                        {
                            Id = "WH-PDX",
                            City = "Portland, OR",
                            FloorDepthM = 20.0,
                            FloorWidthM = 30.0,
                            Latitude = 45.5152,
                            Longitude = -122.6784,
                            Name = "Portland Cold Storage"
                        },
                        new
                        {
                            Id = "WH-BOI",
                            City = "Boise, ID",
                            FloorDepthM = 30.0,
                            FloorWidthM = 50.0,
                            Latitude = 43.615000000000002,
                            Longitude = -116.20229999999999,
                            Name = "Boise Fulfillment Hub"
                        });
                });

            modelBuilder.Entity("SensorDashboard.Api.Data.Alerts.Alert", b =>
                {
                    b.HasOne("SensorDashboard.Api.Data.Metadata.Sensor", "Sensor")
                        .WithMany()
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SensorDashboard.Api.Data.Metadata.Sensor", b =>
                {
                    b.HasOne("SensorDashboard.Api.Data.Metadata.Warehouse", "Warehouse")
                        .WithMany("Sensors")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("SensorDashboard.Api.Data.Metadata.Warehouse", b =>
                {
                    b.Navigation("Sensors");
                });
#pragma warning restore 612, 618
        }
    }
}
